import { getDefaultMiddleware } from '@reduxjs/toolkit';
import configureStore, { MockStore } from 'redux-mock-store';

import { swapiApi } from 'common/api/services/swapi';
import { IAppState } from 'common/models';
import { CategoriesEnum } from 'common/utils/categoriesEnum';

interface IState {
  swapiApi: any;
  swapi: IAppState;
}

export const defaultAppState: IState = {
  swapiApi: {
    queries: {
      'getPlanets("5")': {
        status: 'fulfilled',
        endpointName: 'getPlanets',
        requestId: 'Gu7uDqY-7m6or_V8j1XQW',
        originalArgs: '5',
        startedTimeStamp: 1693861705228,
        data: {
          count: 60,
          next: 'https://swapi.dev/api/planets/?page=6',
          previous: 'https://swapi.dev/api/planets/?page=4',
          results: [
            {
              name: 'Tund',
              rotation_period: '48',
              orbital_period: '1770',
              diameter: '12190',
              climate: 'unknown',
              gravity: 'unknown',
              terrain: 'barren, ash',
              surface_water: 'unknown',
              population: '0',
              residents: ['https://swapi.dev/api/people/50/'],
              films: [],
              created: '2014-12-20T10:07:29.578000Z',
              edited: '2014-12-20T20:58:18.489000Z',
              url: 'https://swapi.dev/api/planets/41/',
            },
            {
              name: 'Haruun Kal',
              rotation_period: '25',
              orbital_period: '383',
              diameter: '10120',
              climate: 'temperate',
              gravity: '0.98',
              terrain: 'toxic cloudsea, plateaus, volcanoes',
              surface_water: 'unknown',
              population: '705300',
              residents: ['https://swapi.dev/api/people/51/'],
              films: [],
              created: '2014-12-20T10:12:28.980000Z',
              edited: '2014-12-20T20:58:18.491000Z',
              url: 'https://swapi.dev/api/planets/42/',
            },
            {
              name: 'Cerea',
              rotation_period: '27',
              orbital_period: '386',
              diameter: 'unknown',
              climate: 'temperate',
              gravity: '1',
              terrain: 'verdant',
              surface_water: '20',
              population: '450000000',
              residents: ['https://swapi.dev/api/people/52/'],
              films: [],
              created: '2014-12-20T10:14:48.178000Z',
              edited: '2014-12-20T20:58:18.493000Z',
              url: 'https://swapi.dev/api/planets/43/',
            },
            {
              name: 'Glee Anselm',
              rotation_period: '33',
              orbital_period: '206',
              diameter: '15600',
              climate: 'tropical, temperate',
              gravity: '1',
              terrain: 'lakes, islands, swamps, seas',
              surface_water: '80',
              population: '500000000',
              residents: ['https://swapi.dev/api/people/53/'],
              films: [],
              created: '2014-12-20T10:18:26.110000Z',
              edited: '2014-12-20T20:58:18.495000Z',
              url: 'https://swapi.dev/api/planets/44/',
            },
            {
              name: 'Iridonia',
              rotation_period: '29',
              orbital_period: '413',
              diameter: 'unknown',
              climate: 'unknown',
              gravity: 'unknown',
              terrain: 'rocky canyons, acid pools',
              surface_water: 'unknown',
              population: 'unknown',
              residents: ['https://swapi.dev/api/people/54/'],
              films: [],
              created: '2014-12-20T10:26:05.788000Z',
              edited: '2014-12-20T20:58:18.497000Z',
              url: 'https://swapi.dev/api/planets/45/',
            },
            {
              name: 'Tholoth',
              rotation_period: 'unknown',
              orbital_period: 'unknown',
              diameter: 'unknown',
              climate: 'unknown',
              gravity: 'unknown',
              terrain: 'unknown',
              surface_water: 'unknown',
              population: 'unknown',
              residents: [],
              films: [],
              created: '2014-12-20T10:28:31.117000Z',
              edited: '2014-12-20T20:58:18.498000Z',
              url: 'https://swapi.dev/api/planets/46/',
            },
            {
              name: 'Iktotch',
              rotation_period: '22',
              orbital_period: '481',
              diameter: 'unknown',
              climate: 'arid, rocky, windy',
              gravity: '1',
              terrain: 'rocky',
              surface_water: 'unknown',
              population: 'unknown',
              residents: ['https://swapi.dev/api/people/56/'],
              films: [],
              created: '2014-12-20T10:31:32.413000Z',
              edited: '2014-12-20T20:58:18.500000Z',
              url: 'https://swapi.dev/api/planets/47/',
            },
            {
              name: 'Quermia',
              rotation_period: 'unknown',
              orbital_period: 'unknown',
              diameter: 'unknown',
              climate: 'unknown',
              gravity: 'unknown',
              terrain: 'unknown',
              surface_water: 'unknown',
              population: 'unknown',
              residents: ['https://swapi.dev/api/people/57/'],
              films: [],
              created: '2014-12-20T10:34:08.249000Z',
              edited: '2014-12-20T20:58:18.502000Z',
              url: 'https://swapi.dev/api/planets/48/',
            },
            {
              name: 'Dorin',
              rotation_period: '22',
              orbital_period: '409',
              diameter: '13400',
              climate: 'temperate',
              gravity: '1',
              terrain: 'unknown',
              surface_water: 'unknown',
              population: 'unknown',
              residents: ['https://swapi.dev/api/people/58/'],
              films: [],
              created: '2014-12-20T10:48:36.141000Z',
              edited: '2014-12-20T20:58:18.504000Z',
              url: 'https://swapi.dev/api/planets/49/',
            },
            {
              name: 'Champala',
              rotation_period: '27',
              orbital_period: '318',
              diameter: 'unknown',
              climate: 'temperate',
              gravity: '1',
              terrain: 'oceans, rainforests, plateaus',
              surface_water: 'unknown',
              population: '3500000000',
              residents: ['https://swapi.dev/api/people/59/'],
              films: [],
              created: '2014-12-20T10:52:51.524000Z',
              edited: '2014-12-20T20:58:18.506000Z',
              url: 'https://swapi.dev/api/planets/50/',
            },
          ],
        },
        fulfilledTimeStamp: 1693861710519,
      },
      'getPeople("2")': {
        status: 'fulfilled',
        endpointName: 'getPeople',
        requestId: 'tkqCrMuOXdjZrNwTd1Pj7',
        originalArgs: '2',
        startedTimeStamp: 1694034509005,
        data: {
          count: 82,
          next: 'https://swapi.dev/api/people/?page=3',
          previous: 'https://swapi.dev/api/people/?page=1',
          results: [
            {
              name: 'Anakin Skywalker',
              height: '188',
              mass: '84',
              hair_color: 'blond',
              skin_color: 'fair',
              eye_color: 'blue',
              birth_year: '41.9BBY',
              gender: 'male',
              homeworld: 'https://swapi.dev/api/planets/1/',
              films: [
                'https://swapi.dev/api/films/4/',
                'https://swapi.dev/api/films/5/',
                'https://swapi.dev/api/films/6/',
              ],
              species: [],
              vehicles: [
                'https://swapi.dev/api/vehicles/44/',
                'https://swapi.dev/api/vehicles/46/',
              ],
              starships: [
                'https://swapi.dev/api/starships/39/',
                'https://swapi.dev/api/starships/59/',
                'https://swapi.dev/api/starships/65/',
              ],
              created: '2014-12-10T16:20:44.310000Z',
              edited: '2014-12-20T21:17:50.327000Z',
              url: 'https://swapi.dev/api/people/11/',
            },
            {
              name: 'Wilhuff Tarkin',
              height: '180',
              mass: 'unknown',
              hair_color: 'auburn, grey',
              skin_color: 'fair',
              eye_color: 'blue',
              birth_year: '64BBY',
              gender: 'male',
              homeworld: 'https://swapi.dev/api/planets/21/',
              films: ['https://swapi.dev/api/films/1/', 'https://swapi.dev/api/films/6/'],
              species: [],
              vehicles: [],
              starships: [],
              created: '2014-12-10T16:26:56.138000Z',
              edited: '2014-12-20T21:17:50.330000Z',
              url: 'https://swapi.dev/api/people/12/',
            },
            {
              name: 'Chewbacca',
              height: '228',
              mass: '112',
              hair_color: 'brown',
              skin_color: 'unknown',
              eye_color: 'blue',
              birth_year: '200BBY',
              gender: 'male',
              homeworld: 'https://swapi.dev/api/planets/14/',
              films: [
                'https://swapi.dev/api/films/1/',
                'https://swapi.dev/api/films/2/',
                'https://swapi.dev/api/films/3/',
                'https://swapi.dev/api/films/6/',
              ],
              species: ['https://swapi.dev/api/species/3/'],
              vehicles: ['https://swapi.dev/api/vehicles/19/'],
              starships: [
                'https://swapi.dev/api/starships/10/',
                'https://swapi.dev/api/starships/22/',
              ],
              created: '2014-12-10T16:42:45.066000Z',
              edited: '2014-12-20T21:17:50.332000Z',
              url: 'https://swapi.dev/api/people/13/',
            },
            {
              name: 'Han Solo',
              height: '180',
              mass: '80',
              hair_color: 'brown',
              skin_color: 'fair',
              eye_color: 'brown',
              birth_year: '29BBY',
              gender: 'male',
              homeworld: 'https://swapi.dev/api/planets/22/',
              films: [
                'https://swapi.dev/api/films/1/',
                'https://swapi.dev/api/films/2/',
                'https://swapi.dev/api/films/3/',
              ],
              species: [],
              vehicles: [],
              starships: [
                'https://swapi.dev/api/starships/10/',
                'https://swapi.dev/api/starships/22/',
              ],
              created: '2014-12-10T16:49:14.582000Z',
              edited: '2014-12-20T21:17:50.334000Z',
              url: 'https://swapi.dev/api/people/14/',
            },
            {
              name: 'Greedo',
              height: '173',
              mass: '74',
              hair_color: 'n/a',
              skin_color: 'green',
              eye_color: 'black',
              birth_year: '44BBY',
              gender: 'male',
              homeworld: 'https://swapi.dev/api/planets/23/',
              films: ['https://swapi.dev/api/films/1/'],
              species: ['https://swapi.dev/api/species/4/'],
              vehicles: [],
              starships: [],
              created: '2014-12-10T17:03:30.334000Z',
              edited: '2014-12-20T21:17:50.336000Z',
              url: 'https://swapi.dev/api/people/15/',
            },
            {
              name: 'Jabba Desilijic Tiure',
              height: '175',
              mass: '1,358',
              hair_color: 'n/a',
              skin_color: 'green-tan, brown',
              eye_color: 'orange',
              birth_year: '600BBY',
              gender: 'hermaphrodite',
              homeworld: 'https://swapi.dev/api/planets/24/',
              films: [
                'https://swapi.dev/api/films/1/',
                'https://swapi.dev/api/films/3/',
                'https://swapi.dev/api/films/4/',
              ],
              species: ['https://swapi.dev/api/species/5/'],
              vehicles: [],
              starships: [],
              created: '2014-12-10T17:11:31.638000Z',
              edited: '2014-12-20T21:17:50.338000Z',
              url: 'https://swapi.dev/api/people/16/',
            },
            {
              name: 'Wedge Antilles',
              height: '170',
              mass: '77',
              hair_color: 'brown',
              skin_color: 'fair',
              eye_color: 'hazel',
              birth_year: '21BBY',
              gender: 'male',
              homeworld: 'https://swapi.dev/api/planets/22/',
              films: [
                'https://swapi.dev/api/films/1/',
                'https://swapi.dev/api/films/2/',
                'https://swapi.dev/api/films/3/',
              ],
              species: [],
              vehicles: ['https://swapi.dev/api/vehicles/14/'],
              starships: ['https://swapi.dev/api/starships/12/'],
              created: '2014-12-12T11:08:06.469000Z',
              edited: '2014-12-20T21:17:50.341000Z',
              url: 'https://swapi.dev/api/people/18/',
            },
            {
              name: 'Jek Tono Porkins',
              height: '180',
              mass: '110',
              hair_color: 'brown',
              skin_color: 'fair',
              eye_color: 'blue',
              birth_year: 'unknown',
              gender: 'male',
              homeworld: 'https://swapi.dev/api/planets/26/',
              films: ['https://swapi.dev/api/films/1/'],
              species: [],
              vehicles: [],
              starships: ['https://swapi.dev/api/starships/12/'],
              created: '2014-12-12T11:16:56.569000Z',
              edited: '2014-12-20T21:17:50.343000Z',
              url: 'https://swapi.dev/api/people/19/',
            },
            {
              name: 'Yoda',
              height: '66',
              mass: '17',
              hair_color: 'white',
              skin_color: 'green',
              eye_color: 'brown',
              birth_year: '896BBY',
              gender: 'male',
              homeworld: 'https://swapi.dev/api/planets/28/',
              films: [
                'https://swapi.dev/api/films/2/',
                'https://swapi.dev/api/films/3/',
                'https://swapi.dev/api/films/4/',
                'https://swapi.dev/api/films/5/',
                'https://swapi.dev/api/films/6/',
              ],
              species: ['https://swapi.dev/api/species/6/'],
              vehicles: [],
              starships: [],
              created: '2014-12-15T12:26:01.042000Z',
              edited: '2014-12-20T21:17:50.345000Z',
              url: 'https://swapi.dev/api/people/20/',
            },
            {
              name: 'Palpatine',
              height: '170',
              mass: '75',
              hair_color: 'grey',
              skin_color: 'pale',
              eye_color: 'yellow',
              birth_year: '82BBY',
              gender: 'male',
              homeworld: 'https://swapi.dev/api/planets/8/',
              films: [
                'https://swapi.dev/api/films/2/',
                'https://swapi.dev/api/films/3/',
                'https://swapi.dev/api/films/4/',
                'https://swapi.dev/api/films/5/',
                'https://swapi.dev/api/films/6/',
              ],
              species: [],
              vehicles: [],
              starships: [],
              created: '2014-12-15T12:48:05.971000Z',
              edited: '2014-12-20T21:17:50.347000Z',
              url: 'https://swapi.dev/api/people/21/',
            },
          ],
        },
        fulfilledTimeStamp: 1694034512773,
      },
    },
    mutations: {},
    provided: {},
    subscriptions: {
      'getPlanets("5")': {
        '2K3Zc9-JJ9rb6dsUcUy0t': {
          pollingInterval: 0,
        },
      },
    },
    config: {
      online: true,
      focused: true,
      middlewareRegistered: true,
      refetchOnFocus: false,
      refetchOnReconnect: false,
      refetchOnMountOrArgChange: false,
      keepUnusedDataFor: 60,
      reducerPath: 'swapiApi',
    },
  },
  swapi: {
    category: {
      title: 'Planets' as CategoriesEnum,
    },
    favorites: {
      planets: [
        {
          name: 'Bespin',
          rotation_period: '12',
          orbital_period: '5110',
          diameter: '118000',
          climate: 'temperate',
          gravity: '1.5 (surface), 1 standard (Cloud City)',
          terrain: 'gas giant',
          surface_water: '0',
          population: '6000000',
          residents: ['https://swapi.dev/api/people/26/'],
          films: ['https://swapi.dev/api/films/2/'],
          created: '2014-12-10T11:43:55.240000Z',
          edited: '2014-12-20T20:58:18.427000Z',
          url: 'https://swapi.dev/api/planets/6/',
        },
        {
          name: 'Endor',
          rotation_period: '18',
          orbital_period: '402',
          diameter: '4900',
          climate: 'temperate',
          gravity: '0.85 standard',
          terrain: 'forests, mountains, lakes',
          surface_water: '8',
          population: '30000000',
          residents: ['https://swapi.dev/api/people/30/'],
          films: ['https://swapi.dev/api/films/3/'],
          created: '2014-12-10T11:50:29.349000Z',
          edited: '2014-12-20T20:58:18.429000Z',
          url: 'https://swapi.dev/api/planets/7/',
        },
        {
          name: 'Coruscant',
          rotation_period: '24',
          orbital_period: '368',
          diameter: '12240',
          climate: 'temperate',
          gravity: '1 standard',
          terrain: 'cityscape, mountains',
          surface_water: 'unknown',
          population: '1000000000000',
          residents: [
            'https://swapi.dev/api/people/34/',
            'https://swapi.dev/api/people/55/',
            'https://swapi.dev/api/people/74/',
          ],
          films: [
            'https://swapi.dev/api/films/3/',
            'https://swapi.dev/api/films/4/',
            'https://swapi.dev/api/films/5/',
            'https://swapi.dev/api/films/6/',
          ],
          created: '2014-12-10T11:54:13.921000Z',
          edited: '2014-12-20T20:58:18.432000Z',
          url: 'https://swapi.dev/api/planets/9/',
        },
      ],
      people: [
        {
          name: 'C-3PO',
          height: '167',
          mass: '75',
          hair_color: 'n/a',
          skin_color: 'gold',
          eye_color: 'yellow',
          birth_year: '112BBY',
          gender: 'n/a',
          homeworld: 'https://swapi.dev/api/planets/1/',
          films: [
            'https://swapi.dev/api/films/1/',
            'https://swapi.dev/api/films/2/',
            'https://swapi.dev/api/films/3/',
            'https://swapi.dev/api/films/4/',
            'https://swapi.dev/api/films/5/',
            'https://swapi.dev/api/films/6/',
          ],
          species: ['https://swapi.dev/api/species/2/'],
          vehicles: [],
          starships: [],
          created: '2014-12-10T15:10:51.357000Z',
          edited: '2014-12-20T21:17:50.309000Z',
          url: 'https://swapi.dev/api/people/2/',
        },
        {
          name: 'R2-D2',
          height: '96',
          mass: '32',
          hair_color: 'n/a',
          skin_color: 'white, blue',
          eye_color: 'red',
          birth_year: '33BBY',
          gender: 'n/a',
          homeworld: 'https://swapi.dev/api/planets/8/',
          films: [
            'https://swapi.dev/api/films/1/',
            'https://swapi.dev/api/films/2/',
            'https://swapi.dev/api/films/3/',
            'https://swapi.dev/api/films/4/',
            'https://swapi.dev/api/films/5/',
            'https://swapi.dev/api/films/6/',
          ],
          species: ['https://swapi.dev/api/species/2/'],
          vehicles: [],
          starships: [],
          created: '2014-12-10T15:11:50.376000Z',
          edited: '2014-12-20T21:17:50.311000Z',
          url: 'https://swapi.dev/api/people/3/',
        },
        {
          name: 'Leia Organa',
          height: '150',
          mass: '49',
          hair_color: 'brown',
          skin_color: 'light',
          eye_color: 'brown',
          birth_year: '19BBY',
          gender: 'female',
          homeworld: 'https://swapi.dev/api/planets/2/',
          films: [
            'https://swapi.dev/api/films/1/',
            'https://swapi.dev/api/films/2/',
            'https://swapi.dev/api/films/3/',
            'https://swapi.dev/api/films/6/',
          ],
          species: [],
          vehicles: ['https://swapi.dev/api/vehicles/30/'],
          starships: [],
          created: '2014-12-10T15:20:09.791000Z',
          edited: '2014-12-20T21:17:50.315000Z',
          url: 'https://swapi.dev/api/people/5/',
        },
        {
          name: 'Beru Whitesun lars',
          height: '165',
          mass: '75',
          hair_color: 'brown',
          skin_color: 'light',
          eye_color: 'blue',
          birth_year: '47BBY',
          gender: 'female',
          homeworld: 'https://swapi.dev/api/planets/1/',
          films: [
            'https://swapi.dev/api/films/1/',
            'https://swapi.dev/api/films/5/',
            'https://swapi.dev/api/films/6/',
          ],
          species: [],
          vehicles: [],
          starships: [],
          created: '2014-12-10T15:53:41.121000Z',
          edited: '2014-12-20T21:17:50.319000Z',
          url: 'https://swapi.dev/api/people/7/',
        },
      ],
      starships: [
        {
          name: 'Theta-class T-2c shuttle',
          model: 'Theta-class T-2c shuttle',
          manufacturer: 'Cygnus Spaceworks',
          cost_in_credits: '1000000',
          length: '18.5',
          max_atmosphering_speed: '2000',
          crew: '5',
          passengers: '16',
          cargo_capacity: '50000',
          consumables: '56 days',
          hyperdrive_rating: '1.0',
          MGLT: 'unknown',
          starship_class: 'transport',
          pilots: [],
          films: ['https://swapi.dev/api/films/6/'],
          created: '2014-12-20T19:48:40.409000Z',
          edited: '2014-12-20T21:23:49.944000Z',
          url: 'https://swapi.dev/api/starships/61/',
        },
        {
          name: 'CR90 corvette',
          model: 'CR90 corvette',
          manufacturer: 'Corellian Engineering Corporation',
          cost_in_credits: '3500000',
          length: '150',
          max_atmosphering_speed: '950',
          crew: '30-165',
          passengers: '600',
          cargo_capacity: '3000000',
          consumables: '1 year',
          hyperdrive_rating: '2.0',
          MGLT: '60',
          starship_class: 'corvette',
          pilots: [],
          films: [
            'https://swapi.dev/api/films/1/',
            'https://swapi.dev/api/films/3/',
            'https://swapi.dev/api/films/6/',
          ],
          created: '2014-12-10T14:20:33.369000Z',
          edited: '2014-12-20T21:23:49.867000Z',
          url: 'https://swapi.dev/api/starships/2/',
        },
        {
          name: 'Jedi Interceptor',
          model: 'Eta-2 Actis-class light interceptor',
          manufacturer: 'Kuat Systems Engineering',
          cost_in_credits: '320000',
          length: '5.47',
          max_atmosphering_speed: '1500',
          crew: '1',
          passengers: '0',
          cargo_capacity: '60',
          consumables: '2 days',
          hyperdrive_rating: '1.0',
          MGLT: 'unknown',
          starship_class: 'starfighter',
          pilots: ['https://swapi.dev/api/people/10/', 'https://swapi.dev/api/people/11/'],
          films: ['https://swapi.dev/api/films/6/'],
          created: '2014-12-20T19:56:57.468000Z',
          edited: '2014-12-20T21:23:49.951000Z',
          url: 'https://swapi.dev/api/starships/65/',
        },
        {
          name: 'Naboo star skiff',
          model: 'J-type star skiff',
          manufacturer:
            'Theed Palace Space Vessel Engineering Corps/Nubia Star Drives, Incorporated',
          cost_in_credits: 'unknown',
          length: '29.2',
          max_atmosphering_speed: '1050',
          crew: '3',
          passengers: '3',
          cargo_capacity: 'unknown',
          consumables: 'unknown',
          hyperdrive_rating: '0.5',
          MGLT: 'unknown',
          starship_class: 'yacht',
          pilots: ['https://swapi.dev/api/people/10/', 'https://swapi.dev/api/people/35/'],
          films: ['https://swapi.dev/api/films/6/'],
          created: '2014-12-20T19:55:15.396000Z',
          edited: '2014-12-20T21:23:49.948000Z',
          url: 'https://swapi.dev/api/starships/64/',
        },
        {
          name: 'Belbullab-22 starfighter',
          model: 'Belbullab-22 starfighter',
          manufacturer: 'Feethan Ottraw Scalable Assemblies',
          cost_in_credits: '168000',
          length: '6.71',
          max_atmosphering_speed: '1100',
          crew: '1',
          passengers: '0',
          cargo_capacity: '140',
          consumables: '7 days',
          hyperdrive_rating: '6',
          MGLT: 'unknown',
          starship_class: 'starfighter',
          pilots: ['https://swapi.dev/api/people/10/', 'https://swapi.dev/api/people/79/'],
          films: ['https://swapi.dev/api/films/6/'],
          created: '2014-12-20T20:38:05.031000Z',
          edited: '2014-12-20T21:23:49.959000Z',
          url: 'https://swapi.dev/api/starships/74/',
        },
        {
          name: 'Sentinel-class landing craft',
          model: 'Sentinel-class landing craft',
          manufacturer: 'Sienar Fleet Systems, Cyngus Spaceworks',
          cost_in_credits: '240000',
          length: '38',
          max_atmosphering_speed: '1000',
          crew: '5',
          passengers: '75',
          cargo_capacity: '180000',
          consumables: '1 month',
          hyperdrive_rating: '1.0',
          MGLT: '70',
          starship_class: 'landing craft',
          pilots: [],
          films: ['https://swapi.dev/api/films/1/'],
          created: '2014-12-10T15:48:00.586000Z',
          edited: '2014-12-20T21:23:49.873000Z',
          url: 'https://swapi.dev/api/starships/5/',
        },
        {
          name: 'X-wing',
          model: 'T-65 X-wing',
          manufacturer: 'Incom Corporation',
          cost_in_credits: '149999',
          length: '12.5',
          max_atmosphering_speed: '1050',
          crew: '1',
          passengers: '0',
          cargo_capacity: '110',
          consumables: '1 week',
          hyperdrive_rating: '1.0',
          MGLT: '100',
          starship_class: 'Starfighter',
          pilots: [
            'https://swapi.dev/api/people/1/',
            'https://swapi.dev/api/people/9/',
            'https://swapi.dev/api/people/18/',
            'https://swapi.dev/api/people/19/',
          ],
          films: [
            'https://swapi.dev/api/films/1/',
            'https://swapi.dev/api/films/2/',
            'https://swapi.dev/api/films/3/',
          ],
          created: '2014-12-12T11:19:05.340000Z',
          edited: '2014-12-20T21:23:49.886000Z',
          url: 'https://swapi.dev/api/starships/12/',
        },
      ],
    },
    planets: {
      planetList: [
        {
          name: 'Naboo',
          rotation_period: '26',
          orbital_period: '312',
          diameter: '12120',
          climate: 'temperate',
          gravity: '1 standard',
          terrain: 'grassy hills, swamps, forests, mountains',
          surface_water: '12',
          population: '4500000000',
          residents: [
            'https://swapi.dev/api/people/3/',
            'https://swapi.dev/api/people/21/',
            'https://swapi.dev/api/people/35/',
            'https://swapi.dev/api/people/36/',
            'https://swapi.dev/api/people/37/',
            'https://swapi.dev/api/people/38/',
            'https://swapi.dev/api/people/39/',
            'https://swapi.dev/api/people/42/',
            'https://swapi.dev/api/people/60/',
            'https://swapi.dev/api/people/61/',
            'https://swapi.dev/api/people/66/',
          ],
          films: [
            'https://swapi.dev/api/films/3/',
            'https://swapi.dev/api/films/4/',
            'https://swapi.dev/api/films/5/',
            'https://swapi.dev/api/films/6/',
          ],
          created: '2014-12-10T11:52:31.066000Z',
          edited: '2014-12-20T20:58:18.430000Z',
          url: 'https://swapi.dev/api/planets/8/',
        },
        {
          name: 'Kamino',
          rotation_period: '27',
          orbital_period: '463',
          diameter: '19720',
          climate: 'temperate',
          gravity: '1 standard',
          terrain: 'ocean',
          surface_water: '100',
          population: '1000000000',
          residents: [
            'https://swapi.dev/api/people/22/',
            'https://swapi.dev/api/people/72/',
            'https://swapi.dev/api/people/73/',
          ],
          films: ['https://swapi.dev/api/films/5/'],
          created: '2014-12-10T12:45:06.577000Z',
          edited: '2014-12-20T20:58:18.434000Z',
          url: 'https://swapi.dev/api/planets/10/',
        },
        {
          name: 'Mustafar',
          rotation_period: '36',
          orbital_period: '412',
          diameter: '4200',
          climate: 'hot',
          gravity: '1 standard',
          terrain: 'volcanoes, lava rivers, mountains, caves',
          surface_water: '0',
          population: '20000',
          residents: [],
          films: ['https://swapi.dev/api/films/6/'],
          created: '2014-12-10T12:50:16.526000Z',
          edited: '2014-12-20T20:58:18.440000Z',
          url: 'https://swapi.dev/api/planets/13/',
        },
        {
          name: 'Eriadu',
          rotation_period: '24',
          orbital_period: '360',
          diameter: '13490',
          climate: 'polluted',
          gravity: '1 standard',
          terrain: 'cityscape',
          surface_water: 'unknown',
          population: '22000000000',
          residents: ['https://swapi.dev/api/people/12/'],
          films: [],
          created: '2014-12-10T16:26:54.384000Z',
          edited: '2014-12-20T20:58:18.454000Z',
          url: 'https://swapi.dev/api/planets/21/',
        },
        {
          name: 'Corellia',
          rotation_period: '25',
          orbital_period: '329',
          diameter: '11000',
          climate: 'temperate',
          gravity: '1 standard',
          terrain: 'plains, urban, hills, forests',
          surface_water: '70',
          population: '3000000000',
          residents: ['https://swapi.dev/api/people/14/', 'https://swapi.dev/api/people/18/'],
          films: [],
          created: '2014-12-10T16:49:12.453000Z',
          edited: '2014-12-20T20:58:18.456000Z',
          url: 'https://swapi.dev/api/planets/22/',
        },
        {
          name: 'Rodia',
          rotation_period: '29',
          orbital_period: '305',
          diameter: '7549',
          climate: 'hot',
          gravity: '1 standard',
          terrain: 'jungles, oceans, urban, swamps',
          surface_water: '60',
          population: '1300000000',
          residents: ['https://swapi.dev/api/people/15/'],
          films: [],
          created: '2014-12-10T17:03:28.110000Z',
          edited: '2014-12-20T20:58:18.458000Z',
          url: 'https://swapi.dev/api/planets/23/',
        },
        {
          name: 'Nal Hutta',
          rotation_period: '87',
          orbital_period: '413',
          diameter: '12150',
          climate: 'temperate',
          gravity: '1 standard',
          terrain: 'urban, oceans, swamps, bogs',
          surface_water: 'unknown',
          population: '7000000000',
          residents: ['https://swapi.dev/api/people/16/'],
          films: [],
          created: '2014-12-10T17:11:29.452000Z',
          edited: '2014-12-20T20:58:18.460000Z',
          url: 'https://swapi.dev/api/planets/24/',
        },
        {
          name: 'Dantooine',
          rotation_period: '25',
          orbital_period: '378',
          diameter: '9830',
          climate: 'temperate',
          gravity: '1 standard',
          terrain: 'oceans, savannas, mountains, grasslands',
          surface_water: 'unknown',
          population: '1000',
          residents: [],
          films: [],
          created: '2014-12-10T17:23:29.896000Z',
          edited: '2014-12-20T20:58:18.461000Z',
          url: 'https://swapi.dev/api/planets/25/',
        },
        {
          name: 'Bestine IV',
          rotation_period: '26',
          orbital_period: '680',
          diameter: '6400',
          climate: 'temperate',
          gravity: 'unknown',
          terrain: 'rocky islands, oceans',
          surface_water: '98',
          population: '62000000',
          residents: ['https://swapi.dev/api/people/19/'],
          films: [],
          created: '2014-12-12T11:16:55.078000Z',
          edited: '2014-12-20T20:58:18.463000Z',
          url: 'https://swapi.dev/api/planets/26/',
        },
        {
          name: 'Ord Mantell',
          rotation_period: '26',
          orbital_period: '334',
          diameter: '14050',
          climate: 'temperate',
          gravity: '1 standard',
          terrain: 'plains, seas, mesas',
          surface_water: '10',
          population: '4000000000',
          residents: [],
          films: ['https://swapi.dev/api/films/2/'],
          created: '2014-12-15T12:23:41.661000Z',
          edited: '2014-12-20T20:58:18.464000Z',
          url: 'https://swapi.dev/api/planets/27/',
        },
        {
          name: 'unknown',
          rotation_period: '0',
          orbital_period: '0',
          diameter: '0',
          climate: 'unknown',
          gravity: 'unknown',
          terrain: 'unknown',
          surface_water: 'unknown',
          population: 'unknown',
          residents: [
            'https://swapi.dev/api/people/20/',
            'https://swapi.dev/api/people/23/',
            'https://swapi.dev/api/people/29/',
            'https://swapi.dev/api/people/32/',
            'https://swapi.dev/api/people/75/',
          ],
          films: [],
          created: '2014-12-15T12:25:59.569000Z',
          edited: '2014-12-20T20:58:18.466000Z',
          url: 'https://swapi.dev/api/planets/28/',
        },
        {
          name: 'Trandosha',
          rotation_period: '25',
          orbital_period: '371',
          diameter: '0',
          climate: 'arid',
          gravity: '0.62 standard',
          terrain: 'mountains, seas, grasslands, deserts',
          surface_water: 'unknown',
          population: '42000000',
          residents: ['https://swapi.dev/api/people/24/'],
          films: [],
          created: '2014-12-15T12:53:47.695000Z',
          edited: '2014-12-20T20:58:18.468000Z',
          url: 'https://swapi.dev/api/planets/29/',
        },
        {
          name: 'Socorro',
          rotation_period: '20',
          orbital_period: '326',
          diameter: '0',
          climate: 'arid',
          gravity: '1 standard',
          terrain: 'deserts, mountains',
          surface_water: 'unknown',
          population: '300000000',
          residents: ['https://swapi.dev/api/people/25/'],
          films: [],
          created: '2014-12-15T12:56:31.121000Z',
          edited: '2014-12-20T20:58:18.469000Z',
          url: 'https://swapi.dev/api/planets/30/',
        },
        {
          name: 'Geonosis',
          rotation_period: '30',
          orbital_period: '256',
          diameter: '11370',
          climate: 'temperate, arid',
          gravity: '0.9 standard',
          terrain: 'rock, desert, mountain, barren',
          surface_water: '5',
          population: '100000000000',
          residents: ['https://swapi.dev/api/people/63/'],
          films: ['https://swapi.dev/api/films/5/'],
          created: '2014-12-10T12:47:22.350000Z',
          edited: '2014-12-20T20:58:18.437000Z',
          url: 'https://swapi.dev/api/planets/11/',
        },
        {
          name: 'Kashyyyk',
          rotation_period: '26',
          orbital_period: '381',
          diameter: '12765',
          climate: 'tropical',
          gravity: '1 standard',
          terrain: 'jungle, forests, lakes, rivers',
          surface_water: '60',
          population: '45000000',
          residents: ['https://swapi.dev/api/people/13/', 'https://swapi.dev/api/people/80/'],
          films: ['https://swapi.dev/api/films/6/'],
          created: '2014-12-10T13:32:00.124000Z',
          edited: '2014-12-20T20:58:18.442000Z',
          url: 'https://swapi.dev/api/planets/14/',
        },
        {
          name: 'Utapau',
          rotation_period: '27',
          orbital_period: '351',
          diameter: '12900',
          climate: 'temperate, arid, windy',
          gravity: '1 standard',
          terrain: 'scrublands, savanna, canyons, sinkholes',
          surface_water: '0.9',
          population: '95000000',
          residents: ['https://swapi.dev/api/people/83/'],
          films: ['https://swapi.dev/api/films/6/'],
          created: '2014-12-10T12:49:01.491000Z',
          edited: '2014-12-20T20:58:18.439000Z',
          url: 'https://swapi.dev/api/planets/12/',
        },
        {
          name: 'Polis Massa',
          rotation_period: '24',
          orbital_period: '590',
          diameter: '0',
          climate: 'artificial temperate ',
          gravity: '0.56 standard',
          terrain: 'airless asteroid',
          surface_water: '0',
          population: '1000000',
          residents: [],
          films: ['https://swapi.dev/api/films/6/'],
          created: '2014-12-10T13:33:46.405000Z',
          edited: '2014-12-20T20:58:18.444000Z',
          url: 'https://swapi.dev/api/planets/15/',
        },
        {
          name: 'Mygeeto',
          rotation_period: '12',
          orbital_period: '167',
          diameter: '10088',
          climate: 'frigid',
          gravity: '1 standard',
          terrain: 'glaciers, mountains, ice canyons',
          surface_water: 'unknown',
          population: '19000000',
          residents: [],
          films: ['https://swapi.dev/api/films/6/'],
          created: '2014-12-10T13:43:39.139000Z',
          edited: '2014-12-20T20:58:18.446000Z',
          url: 'https://swapi.dev/api/planets/16/',
        },
        {
          name: 'Felucia',
          rotation_period: '34',
          orbital_period: '231',
          diameter: '9100',
          climate: 'hot, humid',
          gravity: '0.75 standard',
          terrain: 'fungus forests',
          surface_water: 'unknown',
          population: '8500000',
          residents: [],
          films: ['https://swapi.dev/api/films/6/'],
          created: '2014-12-10T13:44:50.397000Z',
          edited: '2014-12-20T20:58:18.447000Z',
          url: 'https://swapi.dev/api/planets/17/',
        },
        {
          name: 'Cato Neimoidia',
          rotation_period: '25',
          orbital_period: '278',
          diameter: '0',
          climate: 'temperate, moist',
          gravity: '1 standard',
          terrain: 'mountains, fields, forests, rock arches',
          surface_water: 'unknown',
          population: '10000000',
          residents: ['https://swapi.dev/api/people/33/'],
          films: ['https://swapi.dev/api/films/6/'],
          created: '2014-12-10T13:46:28.704000Z',
          edited: '2014-12-20T20:58:18.449000Z',
          url: 'https://swapi.dev/api/planets/18/',
        },
        {
          name: 'Saleucami',
          rotation_period: '26',
          orbital_period: '392',
          diameter: '14920',
          climate: 'hot',
          gravity: 'unknown',
          terrain: 'caves, desert, mountains, volcanoes',
          surface_water: 'unknown',
          population: '1400000000',
          residents: [],
          films: ['https://swapi.dev/api/films/6/'],
          created: '2014-12-10T13:47:46.874000Z',
          edited: '2014-12-20T20:58:18.450000Z',
          url: 'https://swapi.dev/api/planets/19/',
        },
        {
          name: 'Stewjon',
          rotation_period: 'unknown',
          orbital_period: 'unknown',
          diameter: '0',
          climate: 'temperate',
          gravity: '1 standard',
          terrain: 'grass',
          surface_water: 'unknown',
          population: 'unknown',
          residents: ['https://swapi.dev/api/people/10/'],
          films: [],
          created: '2014-12-10T16:16:26.566000Z',
          edited: '2014-12-20T20:58:18.452000Z',
          url: 'https://swapi.dev/api/planets/20/',
        },
        {
          name: 'Tatooine',
          rotation_period: '23',
          orbital_period: '304',
          diameter: '10465',
          climate: 'arid',
          gravity: '1 standard',
          terrain: 'desert',
          surface_water: '1',
          population: '200000',
          residents: [
            'https://swapi.dev/api/people/1/',
            'https://swapi.dev/api/people/2/',
            'https://swapi.dev/api/people/4/',
            'https://swapi.dev/api/people/6/',
            'https://swapi.dev/api/people/7/',
            'https://swapi.dev/api/people/8/',
            'https://swapi.dev/api/people/9/',
            'https://swapi.dev/api/people/11/',
            'https://swapi.dev/api/people/43/',
            'https://swapi.dev/api/people/62/',
          ],
          films: [
            'https://swapi.dev/api/films/1/',
            'https://swapi.dev/api/films/3/',
            'https://swapi.dev/api/films/4/',
            'https://swapi.dev/api/films/5/',
            'https://swapi.dev/api/films/6/',
          ],
          created: '2014-12-09T13:50:49.641000Z',
          edited: '2014-12-20T20:58:18.411000Z',
          url: 'https://swapi.dev/api/planets/1/',
        },
        {
          name: 'Alderaan',
          rotation_period: '24',
          orbital_period: '364',
          diameter: '12500',
          climate: 'temperate',
          gravity: '1 standard',
          terrain: 'grasslands, mountains',
          surface_water: '40',
          population: '2000000000',
          residents: [
            'https://swapi.dev/api/people/5/',
            'https://swapi.dev/api/people/68/',
            'https://swapi.dev/api/people/81/',
          ],
          films: ['https://swapi.dev/api/films/1/', 'https://swapi.dev/api/films/6/'],
          created: '2014-12-10T11:35:48.479000Z',
          edited: '2014-12-20T20:58:18.420000Z',
          url: 'https://swapi.dev/api/planets/2/',
        },
        {
          name: 'Hoth',
          rotation_period: '23',
          orbital_period: '549',
          diameter: '7200',
          climate: 'frozen',
          gravity: '1.1 standard',
          terrain: 'tundra, ice caves, mountain ranges',
          surface_water: '100',
          population: 'unknown',
          residents: [],
          films: ['https://swapi.dev/api/films/2/'],
          created: '2014-12-10T11:39:13.934000Z',
          edited: '2014-12-20T20:58:18.423000Z',
          url: 'https://swapi.dev/api/planets/4/',
        },
        {
          name: 'Eriadu',
          rotation_period: '24',
          orbital_period: '360',
          diameter: '13490',
          climate: 'polluted',
          gravity: '1 standard',
          terrain: 'cityscape',
          surface_water: 'unknown',
          population: '22000000000',
          residents: ['https://swapi.dev/api/people/12/'],
          films: [],
          created: '2014-12-10T16:26:54.384000Z',
          edited: '2014-12-20T20:58:18.454000Z',
          url: 'https://swapi.dev/api/planets/21/',
        },
        {
          name: 'Corellia',
          rotation_period: '25',
          orbital_period: '329',
          diameter: '11000',
          climate: 'temperate',
          gravity: '1 standard',
          terrain: 'plains, urban, hills, forests',
          surface_water: '70',
          population: '3000000000',
          residents: ['https://swapi.dev/api/people/14/', 'https://swapi.dev/api/people/18/'],
          films: [],
          created: '2014-12-10T16:49:12.453000Z',
          edited: '2014-12-20T20:58:18.456000Z',
          url: 'https://swapi.dev/api/planets/22/',
        },
        {
          name: 'Rodia',
          rotation_period: '29',
          orbital_period: '305',
          diameter: '7549',
          climate: 'hot',
          gravity: '1 standard',
          terrain: 'jungles, oceans, urban, swamps',
          surface_water: '60',
          population: '1300000000',
          residents: ['https://swapi.dev/api/people/15/'],
          films: [],
          created: '2014-12-10T17:03:28.110000Z',
          edited: '2014-12-20T20:58:18.458000Z',
          url: 'https://swapi.dev/api/planets/23/',
        },
        {
          name: 'Nal Hutta',
          rotation_period: '87',
          orbital_period: '413',
          diameter: '12150',
          climate: 'temperate',
          gravity: '1 standard',
          terrain: 'urban, oceans, swamps, bogs',
          surface_water: 'unknown',
          population: '7000000000',
          residents: ['https://swapi.dev/api/people/16/'],
          films: [],
          created: '2014-12-10T17:11:29.452000Z',
          edited: '2014-12-20T20:58:18.460000Z',
          url: 'https://swapi.dev/api/planets/24/',
        },
        {
          name: 'Dantooine',
          rotation_period: '25',
          orbital_period: '378',
          diameter: '9830',
          climate: 'temperate',
          gravity: '1 standard',
          terrain: 'oceans, savannas, mountains, grasslands',
          surface_water: 'unknown',
          population: '1000',
          residents: [],
          films: [],
          created: '2014-12-10T17:23:29.896000Z',
          edited: '2014-12-20T20:58:18.461000Z',
          url: 'https://swapi.dev/api/planets/25/',
        },
        {
          name: 'Bestine IV',
          rotation_period: '26',
          orbital_period: '680',
          diameter: '6400',
          climate: 'temperate',
          gravity: 'unknown',
          terrain: 'rocky islands, oceans',
          surface_water: '98',
          population: '62000000',
          residents: ['https://swapi.dev/api/people/19/'],
          films: [],
          created: '2014-12-12T11:16:55.078000Z',
          edited: '2014-12-20T20:58:18.463000Z',
          url: 'https://swapi.dev/api/planets/26/',
        },
        {
          name: 'Ord Mantell',
          rotation_period: '26',
          orbital_period: '334',
          diameter: '14050',
          climate: 'temperate',
          gravity: '1 standard',
          terrain: 'plains, seas, mesas',
          surface_water: '10',
          population: '4000000000',
          residents: [],
          films: ['https://swapi.dev/api/films/2/'],
          created: '2014-12-15T12:23:41.661000Z',
          edited: '2014-12-20T20:58:18.464000Z',
          url: 'https://swapi.dev/api/planets/27/',
        },
        {
          name: 'unknown',
          rotation_period: '0',
          orbital_period: '0',
          diameter: '0',
          climate: 'unknown',
          gravity: 'unknown',
          terrain: 'unknown',
          surface_water: 'unknown',
          population: 'unknown',
          residents: [
            'https://swapi.dev/api/people/20/',
            'https://swapi.dev/api/people/23/',
            'https://swapi.dev/api/people/29/',
            'https://swapi.dev/api/people/32/',
            'https://swapi.dev/api/people/75/',
          ],
          films: [],
          created: '2014-12-15T12:25:59.569000Z',
          edited: '2014-12-20T20:58:18.466000Z',
          url: 'https://swapi.dev/api/planets/28/',
        },
        {
          name: 'Trandosha',
          rotation_period: '25',
          orbital_period: '371',
          diameter: '0',
          climate: 'arid',
          gravity: '0.62 standard',
          terrain: 'mountains, seas, grasslands, deserts',
          surface_water: 'unknown',
          population: '42000000',
          residents: ['https://swapi.dev/api/people/24/'],
          films: [],
          created: '2014-12-15T12:53:47.695000Z',
          edited: '2014-12-20T20:58:18.468000Z',
          url: 'https://swapi.dev/api/planets/29/',
        },
        {
          name: 'Socorro',
          rotation_period: '20',
          orbital_period: '326',
          diameter: '0',
          climate: 'arid',
          gravity: '1 standard',
          terrain: 'deserts, mountains',
          surface_water: 'unknown',
          population: '300000000',
          residents: ['https://swapi.dev/api/people/25/'],
          films: [],
          created: '2014-12-15T12:56:31.121000Z',
          edited: '2014-12-20T20:58:18.469000Z',
          url: 'https://swapi.dev/api/planets/30/',
        },
        {
          name: 'Yavin IV',
          rotation_period: '24',
          orbital_period: '4818',
          diameter: '10200',
          climate: 'temperate, tropical',
          gravity: '1 standard',
          terrain: 'jungle, rainforests',
          surface_water: '8',
          population: '1000',
          residents: [],
          films: ['https://swapi.dev/api/films/1/'],
          created: '2014-12-10T11:37:19.144000Z',
          edited: '2014-12-20T20:58:18.421000Z',
          url: 'https://swapi.dev/api/planets/3/',
        },
        {
          name: 'Dagobah',
          rotation_period: '23',
          orbital_period: '341',
          diameter: '8900',
          climate: 'murky',
          gravity: 'N/A',
          terrain: 'swamp, jungles',
          surface_water: '8',
          population: 'unknown',
          residents: [],
          films: [
            'https://swapi.dev/api/films/2/',
            'https://swapi.dev/api/films/3/',
            'https://swapi.dev/api/films/6/',
          ],
          created: '2014-12-10T11:42:22.590000Z',
          edited: '2014-12-20T20:58:18.425000Z',
          url: 'https://swapi.dev/api/planets/5/',
        },
        {
          name: 'Tund',
          rotation_period: '48',
          orbital_period: '1770',
          diameter: '12190',
          climate: 'unknown',
          gravity: 'unknown',
          terrain: 'barren, ash',
          surface_water: 'unknown',
          population: '0',
          residents: ['https://swapi.dev/api/people/50/'],
          films: [],
          created: '2014-12-20T10:07:29.578000Z',
          edited: '2014-12-20T20:58:18.489000Z',
          url: 'https://swapi.dev/api/planets/41/',
        },
        {
          name: 'Haruun Kal',
          rotation_period: '25',
          orbital_period: '383',
          diameter: '10120',
          climate: 'temperate',
          gravity: '0.98',
          terrain: 'toxic cloudsea, plateaus, volcanoes',
          surface_water: 'unknown',
          population: '705300',
          residents: ['https://swapi.dev/api/people/51/'],
          films: [],
          created: '2014-12-20T10:12:28.980000Z',
          edited: '2014-12-20T20:58:18.491000Z',
          url: 'https://swapi.dev/api/planets/42/',
        },
        {
          name: 'Cerea',
          rotation_period: '27',
          orbital_period: '386',
          diameter: 'unknown',
          climate: 'temperate',
          gravity: '1',
          terrain: 'verdant',
          surface_water: '20',
          population: '450000000',
          residents: ['https://swapi.dev/api/people/52/'],
          films: [],
          created: '2014-12-20T10:14:48.178000Z',
          edited: '2014-12-20T20:58:18.493000Z',
          url: 'https://swapi.dev/api/planets/43/',
        },
        {
          name: 'Glee Anselm',
          rotation_period: '33',
          orbital_period: '206',
          diameter: '15600',
          climate: 'tropical, temperate',
          gravity: '1',
          terrain: 'lakes, islands, swamps, seas',
          surface_water: '80',
          population: '500000000',
          residents: ['https://swapi.dev/api/people/53/'],
          films: [],
          created: '2014-12-20T10:18:26.110000Z',
          edited: '2014-12-20T20:58:18.495000Z',
          url: 'https://swapi.dev/api/planets/44/',
        },
        {
          name: 'Iridonia',
          rotation_period: '29',
          orbital_period: '413',
          diameter: 'unknown',
          climate: 'unknown',
          gravity: 'unknown',
          terrain: 'rocky canyons, acid pools',
          surface_water: 'unknown',
          population: 'unknown',
          residents: ['https://swapi.dev/api/people/54/'],
          films: [],
          created: '2014-12-20T10:26:05.788000Z',
          edited: '2014-12-20T20:58:18.497000Z',
          url: 'https://swapi.dev/api/planets/45/',
        },
        {
          name: 'Tholoth',
          rotation_period: 'unknown',
          orbital_period: 'unknown',
          diameter: 'unknown',
          climate: 'unknown',
          gravity: 'unknown',
          terrain: 'unknown',
          surface_water: 'unknown',
          population: 'unknown',
          residents: [],
          films: [],
          created: '2014-12-20T10:28:31.117000Z',
          edited: '2014-12-20T20:58:18.498000Z',
          url: 'https://swapi.dev/api/planets/46/',
        },
        {
          name: 'Iktotch',
          rotation_period: '22',
          orbital_period: '481',
          diameter: 'unknown',
          climate: 'arid, rocky, windy',
          gravity: '1',
          terrain: 'rocky',
          surface_water: 'unknown',
          population: 'unknown',
          residents: ['https://swapi.dev/api/people/56/'],
          films: [],
          created: '2014-12-20T10:31:32.413000Z',
          edited: '2014-12-20T20:58:18.500000Z',
          url: 'https://swapi.dev/api/planets/47/',
        },
        {
          name: 'Quermia',
          rotation_period: 'unknown',
          orbital_period: 'unknown',
          diameter: 'unknown',
          climate: 'unknown',
          gravity: 'unknown',
          terrain: 'unknown',
          surface_water: 'unknown',
          population: 'unknown',
          residents: ['https://swapi.dev/api/people/57/'],
          films: [],
          created: '2014-12-20T10:34:08.249000Z',
          edited: '2014-12-20T20:58:18.502000Z',
          url: 'https://swapi.dev/api/planets/48/',
        },
        {
          name: 'Dorin',
          rotation_period: '22',
          orbital_period: '409',
          diameter: '13400',
          climate: 'temperate',
          gravity: '1',
          terrain: 'unknown',
          surface_water: 'unknown',
          population: 'unknown',
          residents: ['https://swapi.dev/api/people/58/'],
          films: [],
          created: '2014-12-20T10:48:36.141000Z',
          edited: '2014-12-20T20:58:18.504000Z',
          url: 'https://swapi.dev/api/planets/49/',
        },
        {
          name: 'Champala',
          rotation_period: '27',
          orbital_period: '318',
          diameter: 'unknown',
          climate: 'temperate',
          gravity: '1',
          terrain: 'oceans, rainforests, plateaus',
          surface_water: 'unknown',
          population: '3500000000',
          residents: ['https://swapi.dev/api/people/59/'],
          films: [],
          created: '2014-12-20T10:52:51.524000Z',
          edited: '2014-12-20T20:58:18.506000Z',
          url: 'https://swapi.dev/api/planets/50/',
        },
      ],
      pageNumber: 5,
    },
    people: {
      peopleList: [
        {
          name: 'Darth Vader',
          height: '202',
          mass: '136',
          hair_color: 'none',
          skin_color: 'white',
          eye_color: 'yellow',
          birth_year: '41.9BBY',
          gender: 'male',
          homeworld: 'https://swapi.dev/api/planets/1/',
          films: [
            'https://swapi.dev/api/films/1/',
            'https://swapi.dev/api/films/2/',
            'https://swapi.dev/api/films/3/',
            'https://swapi.dev/api/films/6/',
          ],
          species: [],
          vehicles: [],
          starships: ['https://swapi.dev/api/starships/13/'],
          created: '2014-12-10T15:18:20.704000Z',
          edited: '2014-12-20T21:17:50.313000Z',
          url: 'https://swapi.dev/api/people/4/',
        },
        {
          name: 'Owen Lars',
          height: '178',
          mass: '120',
          hair_color: 'brown, grey',
          skin_color: 'light',
          eye_color: 'blue',
          birth_year: '52BBY',
          gender: 'male',
          homeworld: 'https://swapi.dev/api/planets/1/',
          films: [
            'https://swapi.dev/api/films/1/',
            'https://swapi.dev/api/films/5/',
            'https://swapi.dev/api/films/6/',
          ],
          species: [],
          vehicles: [],
          starships: [],
          created: '2014-12-10T15:52:14.024000Z',
          edited: '2014-12-20T21:17:50.317000Z',
          url: 'https://swapi.dev/api/people/6/',
        },
        {
          name: 'R5-D4',
          height: '97',
          mass: '32',
          hair_color: 'n/a',
          skin_color: 'white, red',
          eye_color: 'red',
          birth_year: 'unknown',
          gender: 'n/a',
          homeworld: 'https://swapi.dev/api/planets/1/',
          films: ['https://swapi.dev/api/films/1/'],
          species: ['https://swapi.dev/api/species/2/'],
          vehicles: [],
          starships: [],
          created: '2014-12-10T15:57:50.959000Z',
          edited: '2014-12-20T21:17:50.321000Z',
          url: 'https://swapi.dev/api/people/8/',
        },
        {
          name: 'Biggs Darklighter',
          height: '183',
          mass: '84',
          hair_color: 'black',
          skin_color: 'light',
          eye_color: 'brown',
          birth_year: '24BBY',
          gender: 'male',
          homeworld: 'https://swapi.dev/api/planets/1/',
          films: ['https://swapi.dev/api/films/1/'],
          species: [],
          vehicles: [],
          starships: ['https://swapi.dev/api/starships/12/'],
          created: '2014-12-10T15:59:50.509000Z',
          edited: '2014-12-20T21:17:50.323000Z',
          url: 'https://swapi.dev/api/people/9/',
        },
        {
          name: 'Obi-Wan Kenobi',
          height: '182',
          mass: '77',
          hair_color: 'auburn, white',
          skin_color: 'fair',
          eye_color: 'blue-gray',
          birth_year: '57BBY',
          gender: 'male',
          homeworld: 'https://swapi.dev/api/planets/20/',
          films: [
            'https://swapi.dev/api/films/1/',
            'https://swapi.dev/api/films/2/',
            'https://swapi.dev/api/films/3/',
            'https://swapi.dev/api/films/4/',
            'https://swapi.dev/api/films/5/',
            'https://swapi.dev/api/films/6/',
          ],
          species: [],
          vehicles: ['https://swapi.dev/api/vehicles/38/'],
          starships: [
            'https://swapi.dev/api/starships/48/',
            'https://swapi.dev/api/starships/59/',
            'https://swapi.dev/api/starships/64/',
            'https://swapi.dev/api/starships/65/',
            'https://swapi.dev/api/starships/74/',
          ],
          created: '2014-12-10T16:16:29.192000Z',
          edited: '2014-12-20T21:17:50.325000Z',
          url: 'https://swapi.dev/api/people/10/',
        },
        {
          name: 'Anakin Skywalker',
          height: '188',
          mass: '84',
          hair_color: 'blond',
          skin_color: 'fair',
          eye_color: 'blue',
          birth_year: '41.9BBY',
          gender: 'male',
          homeworld: 'https://swapi.dev/api/planets/1/',
          films: [
            'https://swapi.dev/api/films/4/',
            'https://swapi.dev/api/films/5/',
            'https://swapi.dev/api/films/6/',
          ],
          species: [],
          vehicles: ['https://swapi.dev/api/vehicles/44/', 'https://swapi.dev/api/vehicles/46/'],
          starships: [
            'https://swapi.dev/api/starships/39/',
            'https://swapi.dev/api/starships/59/',
            'https://swapi.dev/api/starships/65/',
          ],
          created: '2014-12-10T16:20:44.310000Z',
          edited: '2014-12-20T21:17:50.327000Z',
          url: 'https://swapi.dev/api/people/11/',
        },
        {
          name: 'Wilhuff Tarkin',
          height: '180',
          mass: 'unknown',
          hair_color: 'auburn, grey',
          skin_color: 'fair',
          eye_color: 'blue',
          birth_year: '64BBY',
          gender: 'male',
          homeworld: 'https://swapi.dev/api/planets/21/',
          films: ['https://swapi.dev/api/films/1/', 'https://swapi.dev/api/films/6/'],
          species: [],
          vehicles: [],
          starships: [],
          created: '2014-12-10T16:26:56.138000Z',
          edited: '2014-12-20T21:17:50.330000Z',
          url: 'https://swapi.dev/api/people/12/',
        },
        {
          name: 'Chewbacca',
          height: '228',
          mass: '112',
          hair_color: 'brown',
          skin_color: 'unknown',
          eye_color: 'blue',
          birth_year: '200BBY',
          gender: 'male',
          homeworld: 'https://swapi.dev/api/planets/14/',
          films: [
            'https://swapi.dev/api/films/1/',
            'https://swapi.dev/api/films/2/',
            'https://swapi.dev/api/films/3/',
            'https://swapi.dev/api/films/6/',
          ],
          species: ['https://swapi.dev/api/species/3/'],
          vehicles: ['https://swapi.dev/api/vehicles/19/'],
          starships: ['https://swapi.dev/api/starships/10/', 'https://swapi.dev/api/starships/22/'],
          created: '2014-12-10T16:42:45.066000Z',
          edited: '2014-12-20T21:17:50.332000Z',
          url: 'https://swapi.dev/api/people/13/',
        },
        {
          name: 'Han Solo',
          height: '180',
          mass: '80',
          hair_color: 'brown',
          skin_color: 'fair',
          eye_color: 'brown',
          birth_year: '29BBY',
          gender: 'male',
          homeworld: 'https://swapi.dev/api/planets/22/',
          films: [
            'https://swapi.dev/api/films/1/',
            'https://swapi.dev/api/films/2/',
            'https://swapi.dev/api/films/3/',
          ],
          species: [],
          vehicles: [],
          starships: ['https://swapi.dev/api/starships/10/', 'https://swapi.dev/api/starships/22/'],
          created: '2014-12-10T16:49:14.582000Z',
          edited: '2014-12-20T21:17:50.334000Z',
          url: 'https://swapi.dev/api/people/14/',
        },
        {
          name: 'Greedo',
          height: '173',
          mass: '74',
          hair_color: 'n/a',
          skin_color: 'green',
          eye_color: 'black',
          birth_year: '44BBY',
          gender: 'male',
          homeworld: 'https://swapi.dev/api/planets/23/',
          films: ['https://swapi.dev/api/films/1/'],
          species: ['https://swapi.dev/api/species/4/'],
          vehicles: [],
          starships: [],
          created: '2014-12-10T17:03:30.334000Z',
          edited: '2014-12-20T21:17:50.336000Z',
          url: 'https://swapi.dev/api/people/15/',
        },
        {
          name: 'Jabba Desilijic Tiure',
          height: '175',
          mass: '1,358',
          hair_color: 'n/a',
          skin_color: 'green-tan, brown',
          eye_color: 'orange',
          birth_year: '600BBY',
          gender: 'hermaphrodite',
          homeworld: 'https://swapi.dev/api/planets/24/',
          films: [
            'https://swapi.dev/api/films/1/',
            'https://swapi.dev/api/films/3/',
            'https://swapi.dev/api/films/4/',
          ],
          species: ['https://swapi.dev/api/species/5/'],
          vehicles: [],
          starships: [],
          created: '2014-12-10T17:11:31.638000Z',
          edited: '2014-12-20T21:17:50.338000Z',
          url: 'https://swapi.dev/api/people/16/',
        },
        {
          name: 'Wedge Antilles',
          height: '170',
          mass: '77',
          hair_color: 'brown',
          skin_color: 'fair',
          eye_color: 'hazel',
          birth_year: '21BBY',
          gender: 'male',
          homeworld: 'https://swapi.dev/api/planets/22/',
          films: [
            'https://swapi.dev/api/films/1/',
            'https://swapi.dev/api/films/2/',
            'https://swapi.dev/api/films/3/',
          ],
          species: [],
          vehicles: ['https://swapi.dev/api/vehicles/14/'],
          starships: ['https://swapi.dev/api/starships/12/'],
          created: '2014-12-12T11:08:06.469000Z',
          edited: '2014-12-20T21:17:50.341000Z',
          url: 'https://swapi.dev/api/people/18/',
        },
        {
          name: 'Jek Tono Porkins',
          height: '180',
          mass: '110',
          hair_color: 'brown',
          skin_color: 'fair',
          eye_color: 'blue',
          birth_year: 'unknown',
          gender: 'male',
          homeworld: 'https://swapi.dev/api/planets/26/',
          films: ['https://swapi.dev/api/films/1/'],
          species: [],
          vehicles: [],
          starships: ['https://swapi.dev/api/starships/12/'],
          created: '2014-12-12T11:16:56.569000Z',
          edited: '2014-12-20T21:17:50.343000Z',
          url: 'https://swapi.dev/api/people/19/',
        },
        {
          name: 'Yoda',
          height: '66',
          mass: '17',
          hair_color: 'white',
          skin_color: 'green',
          eye_color: 'brown',
          birth_year: '896BBY',
          gender: 'male',
          homeworld: 'https://swapi.dev/api/planets/28/',
          films: [
            'https://swapi.dev/api/films/2/',
            'https://swapi.dev/api/films/3/',
            'https://swapi.dev/api/films/4/',
            'https://swapi.dev/api/films/5/',
            'https://swapi.dev/api/films/6/',
          ],
          species: ['https://swapi.dev/api/species/6/'],
          vehicles: [],
          starships: [],
          created: '2014-12-15T12:26:01.042000Z',
          edited: '2014-12-20T21:17:50.345000Z',
          url: 'https://swapi.dev/api/people/20/',
        },
        {
          name: 'Palpatine',
          height: '170',
          mass: '75',
          hair_color: 'grey',
          skin_color: 'pale',
          eye_color: 'yellow',
          birth_year: '82BBY',
          gender: 'male',
          homeworld: 'https://swapi.dev/api/planets/8/',
          films: [
            'https://swapi.dev/api/films/2/',
            'https://swapi.dev/api/films/3/',
            'https://swapi.dev/api/films/4/',
            'https://swapi.dev/api/films/5/',
            'https://swapi.dev/api/films/6/',
          ],
          species: [],
          vehicles: [],
          starships: [],
          created: '2014-12-15T12:48:05.971000Z',
          edited: '2014-12-20T21:17:50.347000Z',
          url: 'https://swapi.dev/api/people/21/',
        },
        {
          name: 'Luke Skywalker',
          height: '172',
          mass: '77',
          hair_color: 'blond',
          skin_color: 'fair',
          eye_color: 'blue',
          birth_year: '19BBY',
          gender: 'male',
          homeworld: 'https://swapi.dev/api/planets/1/',
          films: [
            'https://swapi.dev/api/films/1/',
            'https://swapi.dev/api/films/2/',
            'https://swapi.dev/api/films/3/',
            'https://swapi.dev/api/films/6/',
          ],
          species: [],
          vehicles: ['https://swapi.dev/api/vehicles/14/', 'https://swapi.dev/api/vehicles/30/'],
          starships: ['https://swapi.dev/api/starships/12/', 'https://swapi.dev/api/starships/22/'],
          created: '2014-12-09T13:50:51.644000Z',
          edited: '2014-12-20T21:17:56.891000Z',
          url: 'https://swapi.dev/api/people/1/',
        },
      ],
      pageNumber: 2,
    },
    starships: {
      starshipList: [
        {
          name: 'V-wing',
          model: 'Alpha-3 Nimbus-class V-wing starfighter',
          manufacturer: 'Kuat Systems Engineering',
          cost_in_credits: '102500',
          length: '7.9',
          max_atmosphering_speed: '1050',
          crew: '1',
          passengers: '0',
          cargo_capacity: '60',
          consumables: '15 hours',
          hyperdrive_rating: '1.0',
          MGLT: 'unknown',
          starship_class: 'starfighter',
          pilots: [],
          films: ['https://swapi.dev/api/films/6/'],
          created: '2014-12-20T20:43:04.349000Z',
          edited: '2014-12-20T21:23:49.961000Z',
          url: 'https://swapi.dev/api/starships/75/',
        },
        {
          name: 'Y-wing',
          model: 'BTL Y-wing',
          manufacturer: 'Koensayr Manufacturing',
          cost_in_credits: '134999',
          length: '14',
          max_atmosphering_speed: '1000km',
          crew: '2',
          passengers: '0',
          cargo_capacity: '110',
          consumables: '1 week',
          hyperdrive_rating: '1.0',
          MGLT: '80',
          starship_class: 'assault starfighter',
          pilots: [],
          films: [
            'https://swapi.dev/api/films/1/',
            'https://swapi.dev/api/films/2/',
            'https://swapi.dev/api/films/3/',
          ],
          created: '2014-12-12T11:00:39.817000Z',
          edited: '2014-12-20T21:23:49.883000Z',
          url: 'https://swapi.dev/api/starships/11/',
        },
        {
          name: 'Millennium Falcon',
          model: 'YT-1300 light freighter',
          manufacturer: 'Corellian Engineering Corporation',
          cost_in_credits: '100000',
          length: '34.37',
          max_atmosphering_speed: '1050',
          crew: '4',
          passengers: '6',
          cargo_capacity: '100000',
          consumables: '2 months',
          hyperdrive_rating: '0.5',
          MGLT: '75',
          starship_class: 'Light freighter',
          pilots: [
            'https://swapi.dev/api/people/13/',
            'https://swapi.dev/api/people/14/',
            'https://swapi.dev/api/people/25/',
            'https://swapi.dev/api/people/31/',
          ],
          films: [
            'https://swapi.dev/api/films/1/',
            'https://swapi.dev/api/films/2/',
            'https://swapi.dev/api/films/3/',
          ],
          created: '2014-12-10T16:59:45.094000Z',
          edited: '2014-12-20T21:23:49.880000Z',
          url: 'https://swapi.dev/api/starships/10/',
        },
        {
          name: 'TIE Advanced x1',
          model: 'Twin Ion Engine Advanced x1',
          manufacturer: 'Sienar Fleet Systems',
          cost_in_credits: 'unknown',
          length: '9.2',
          max_atmosphering_speed: '1200',
          crew: '1',
          passengers: '0',
          cargo_capacity: '150',
          consumables: '5 days',
          hyperdrive_rating: '1.0',
          MGLT: '105',
          starship_class: 'Starfighter',
          pilots: ['https://swapi.dev/api/people/4/'],
          films: ['https://swapi.dev/api/films/1/'],
          created: '2014-12-12T11:21:32.991000Z',
          edited: '2014-12-20T21:23:49.889000Z',
          url: 'https://swapi.dev/api/starships/13/',
        },
        {
          name: 'Rebel transport',
          model: 'GR-75 medium transport',
          manufacturer: 'Gallofree Yards, Inc.',
          cost_in_credits: 'unknown',
          length: '90',
          max_atmosphering_speed: '650',
          crew: '6',
          passengers: '90',
          cargo_capacity: '19000000',
          consumables: '6 months',
          hyperdrive_rating: '4.0',
          MGLT: '20',
          starship_class: 'Medium transport',
          pilots: [],
          films: ['https://swapi.dev/api/films/2/', 'https://swapi.dev/api/films/3/'],
          created: '2014-12-15T12:34:52.264000Z',
          edited: '2014-12-20T21:23:49.895000Z',
          url: 'https://swapi.dev/api/starships/17/',
        },
        {
          name: 'Executor',
          model: 'Executor-class star dreadnought',
          manufacturer: 'Kuat Drive Yards, Fondor Shipyards',
          cost_in_credits: '1143350000',
          length: '19000',
          max_atmosphering_speed: 'n/a',
          crew: '279,144',
          passengers: '38000',
          cargo_capacity: '250000000',
          consumables: '6 years',
          hyperdrive_rating: '2.0',
          MGLT: '40',
          starship_class: 'Star dreadnought',
          pilots: [],
          films: ['https://swapi.dev/api/films/2/', 'https://swapi.dev/api/films/3/'],
          created: '2014-12-15T12:31:42.547000Z',
          edited: '2014-12-20T21:23:49.893000Z',
          url: 'https://swapi.dev/api/starships/15/',
        },
        {
          name: 'Scimitar',
          model: 'Star Courier',
          manufacturer: 'Republic Sienar Systems',
          cost_in_credits: '55000000',
          length: '26.5',
          max_atmosphering_speed: '1180',
          crew: '1',
          passengers: '6',
          cargo_capacity: '2500000',
          consumables: '30 days',
          hyperdrive_rating: '1.5',
          MGLT: 'unknown',
          starship_class: 'Space Transport',
          pilots: ['https://swapi.dev/api/people/44/'],
          films: ['https://swapi.dev/api/films/4/'],
          created: '2014-12-20T09:39:56.116000Z',
          edited: '2014-12-20T21:23:49.922000Z',
          url: 'https://swapi.dev/api/starships/41/',
        },
        {
          name: 'Star Destroyer',
          model: 'Imperial I-class Star Destroyer',
          manufacturer: 'Kuat Drive Yards',
          cost_in_credits: '150000000',
          length: '1,600',
          max_atmosphering_speed: '975',
          crew: '47,060',
          passengers: 'n/a',
          cargo_capacity: '36000000',
          consumables: '2 years',
          hyperdrive_rating: '2.0',
          MGLT: '60',
          starship_class: 'Star Destroyer',
          pilots: [],
          films: [
            'https://swapi.dev/api/films/1/',
            'https://swapi.dev/api/films/2/',
            'https://swapi.dev/api/films/3/',
          ],
          created: '2014-12-10T15:08:19.848000Z',
          edited: '2014-12-20T21:23:49.870000Z',
          url: 'https://swapi.dev/api/starships/3/',
        },
        {
          name: 'J-type diplomatic barge',
          model: 'J-type diplomatic barge',
          manufacturer: 'Theed Palace Space Vessel Engineering Corps, Nubia Star Drives',
          cost_in_credits: '2000000',
          length: '39',
          max_atmosphering_speed: '2000',
          crew: '5',
          passengers: '10',
          cargo_capacity: 'unknown',
          consumables: '1 year',
          hyperdrive_rating: '0.7',
          MGLT: 'unknown',
          starship_class: 'Diplomatic barge',
          pilots: [],
          films: ['https://swapi.dev/api/films/5/'],
          created: '2014-12-20T11:05:51.237000Z',
          edited: '2014-12-20T21:23:49.925000Z',
          url: 'https://swapi.dev/api/starships/43/',
        },
        {
          name: 'AA-9 Coruscant freighter',
          model: 'Botajef AA-9 Freighter-Liner',
          manufacturer: 'Botajef Shipyards',
          cost_in_credits: 'unknown',
          length: '390',
          max_atmosphering_speed: 'unknown',
          crew: 'unknown',
          passengers: '30000',
          cargo_capacity: 'unknown',
          consumables: 'unknown',
          hyperdrive_rating: 'unknown',
          MGLT: 'unknown',
          starship_class: 'freighter',
          pilots: [],
          films: ['https://swapi.dev/api/films/5/'],
          created: '2014-12-20T17:24:23.509000Z',
          edited: '2014-12-20T21:23:49.928000Z',
          url: 'https://swapi.dev/api/starships/47/',
        },
        {
          name: 'Jedi starfighter',
          model: 'Delta-7 Aethersprite-class interceptor',
          manufacturer: 'Kuat Systems Engineering',
          cost_in_credits: '180000',
          length: '8',
          max_atmosphering_speed: '1150',
          crew: '1',
          passengers: '0',
          cargo_capacity: '60',
          consumables: '7 days',
          hyperdrive_rating: '1.0',
          MGLT: 'unknown',
          starship_class: 'Starfighter',
          pilots: ['https://swapi.dev/api/people/10/', 'https://swapi.dev/api/people/58/'],
          films: ['https://swapi.dev/api/films/5/', 'https://swapi.dev/api/films/6/'],
          created: '2014-12-20T17:35:23.906000Z',
          edited: '2014-12-20T21:23:49.930000Z',
          url: 'https://swapi.dev/api/starships/48/',
        },
        {
          name: 'H-type Nubian yacht',
          model: 'H-type Nubian yacht',
          manufacturer: 'Theed Palace Space Vessel Engineering Corps',
          cost_in_credits: 'unknown',
          length: '47.9',
          max_atmosphering_speed: '8000',
          crew: '4',
          passengers: 'unknown',
          cargo_capacity: 'unknown',
          consumables: 'unknown',
          hyperdrive_rating: '0.9',
          MGLT: 'unknown',
          starship_class: 'yacht',
          pilots: ['https://swapi.dev/api/people/35/'],
          films: ['https://swapi.dev/api/films/5/'],
          created: '2014-12-20T17:46:46.847000Z',
          edited: '2014-12-20T21:23:49.932000Z',
          url: 'https://swapi.dev/api/starships/49/',
        },
        {
          name: 'Republic Assault ship',
          model: 'Acclamator I-class assault ship',
          manufacturer: 'Rothana Heavy Engineering',
          cost_in_credits: 'unknown',
          length: '752',
          max_atmosphering_speed: 'unknown',
          crew: '700',
          passengers: '16000',
          cargo_capacity: '11250000',
          consumables: '2 years',
          hyperdrive_rating: '0.6',
          MGLT: 'unknown',
          starship_class: 'assault ship',
          pilots: [],
          films: ['https://swapi.dev/api/films/5/'],
          created: '2014-12-20T18:08:42.926000Z',
          edited: '2014-12-20T21:23:49.935000Z',
          url: 'https://swapi.dev/api/starships/52/',
        },
        {
          name: 'Solar Sailer',
          model: 'Punworcca 116-class interstellar sloop',
          manufacturer: 'Huppla Pasa Tisc Shipwrights Collective',
          cost_in_credits: '35700',
          length: '15.2',
          max_atmosphering_speed: '1600',
          crew: '3',
          passengers: '11',
          cargo_capacity: '240',
          consumables: '7 days',
          hyperdrive_rating: '1.5',
          MGLT: 'unknown',
          starship_class: 'yacht',
          pilots: [],
          films: ['https://swapi.dev/api/films/5/'],
          created: '2014-12-20T18:37:56.969000Z',
          edited: '2014-12-20T21:23:49.937000Z',
          url: 'https://swapi.dev/api/starships/58/',
        },
        {
          name: 'Trade Federation cruiser',
          model: 'Providence-class carrier/destroyer',
          manufacturer: 'Rendili StarDrive, Free Dac Volunteers Engineering corps.',
          cost_in_credits: '125000000',
          length: '1088',
          max_atmosphering_speed: '1050',
          crew: '600',
          passengers: '48247',
          cargo_capacity: '50000000',
          consumables: '4 years',
          hyperdrive_rating: '1.5',
          MGLT: 'unknown',
          starship_class: 'capital ship',
          pilots: ['https://swapi.dev/api/people/10/', 'https://swapi.dev/api/people/11/'],
          films: ['https://swapi.dev/api/films/6/'],
          created: '2014-12-20T19:40:21.902000Z',
          edited: '2014-12-20T21:23:49.941000Z',
          url: 'https://swapi.dev/api/starships/59/',
        },
        {
          name: 'Republic attack cruiser',
          model: 'Senator-class Star Destroyer',
          manufacturer: 'Kuat Drive Yards, Allanteen Six shipyards',
          cost_in_credits: '59000000',
          length: '1137',
          max_atmosphering_speed: '975',
          crew: '7400',
          passengers: '2000',
          cargo_capacity: '20000000',
          consumables: '2 years',
          hyperdrive_rating: '1.0',
          MGLT: 'unknown',
          starship_class: 'star destroyer',
          pilots: [],
          films: ['https://swapi.dev/api/films/6/'],
          created: '2014-12-20T19:52:56.232000Z',
          edited: '2014-12-20T21:23:49.946000Z',
          url: 'https://swapi.dev/api/starships/63/',
        },
        {
          name: 'Death Star',
          model: 'DS-1 Orbital Battle Station',
          manufacturer: 'Imperial Department of Military Research, Sienar Fleet Systems',
          cost_in_credits: '1000000000000',
          length: '120000',
          max_atmosphering_speed: 'n/a',
          crew: '342,953',
          passengers: '843,342',
          cargo_capacity: '1000000000000',
          consumables: '3 years',
          hyperdrive_rating: '4.0',
          MGLT: '10',
          starship_class: 'Deep Space Mobile Battlestation',
          pilots: [],
          films: ['https://swapi.dev/api/films/1/'],
          created: '2014-12-10T16:36:50.509000Z',
          edited: '2014-12-20T21:26:24.783000Z',
          url: 'https://swapi.dev/api/starships/9/',
        },
        {
          name: 'Banking clan frigte',
          model: 'Munificent-class star frigate',
          manufacturer: 'Hoersch-Kessel Drive, Inc, Gwori Revolutionary Industries',
          cost_in_credits: '57000000',
          length: '825',
          max_atmosphering_speed: 'unknown',
          crew: '200',
          passengers: 'unknown',
          cargo_capacity: '40000000',
          consumables: '2 years',
          hyperdrive_rating: '1.0',
          MGLT: 'unknown',
          starship_class: 'cruiser',
          pilots: [],
          films: ['https://swapi.dev/api/films/6/'],
          created: '2014-12-20T20:07:11.538000Z',
          edited: '2014-12-20T21:23:49.956000Z',
          url: 'https://swapi.dev/api/starships/68/',
        },
        {
          name: 'arc-170',
          model: 'Aggressive Reconnaissance-170 starfighte',
          manufacturer: 'Incom Corporation, Subpro Corporation',
          cost_in_credits: '155000',
          length: '14.5',
          max_atmosphering_speed: '1000',
          crew: '3',
          passengers: '0',
          cargo_capacity: '110',
          consumables: '5 days',
          hyperdrive_rating: '1.0',
          MGLT: '100',
          starship_class: 'starfighter',
          pilots: [],
          films: ['https://swapi.dev/api/films/6/'],
          created: '2014-12-20T20:03:48.603000Z',
          edited: '2014-12-20T21:23:49.953000Z',
          url: 'https://swapi.dev/api/starships/66/',
        },
      ],
      pageNumber: 4,
    },
  },
};

const mockStore = configureStore(
  getDefaultMiddleware({ serializableCheck: false, immutableCheck: false }).concat(
    swapiApi.middleware
  )
);
const store = (appState = {} as IAppState): MockStore =>
  mockStore({ ...defaultAppState, ...appState });

export default store;
